language: node_js

node_js:
  - stable

install:
  - yarn install

#script:
#  - yarn run cover

# Send coverage data to Coveralls
#after_script: "coverage"


script:
  - yarn run cover

# Send coverage data to Coveralls
after_script: "yarn run coverall"
